apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-chart.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-chart.metadataLabels" . | nindent 4 }}
  {{- if ( hasKey .Values.metadata "annotations" ) }}
  annotations:
    {{- include "app-chart.metadataAnnotations" . | nindent 4 }}
  {{- end }}
{{- if ( hasKey .Values.advanced.common.app_chart.values  "image_pull_secrets") }}
{{- if gt (len .Values.advanced.common.app_chart.values.image_pull_secrets) 0 }}
imagePullSecrets:
{{- include "app-chart.imagePullSecrets" . | indent 2 }}
{{- end }}
{{- end }}
