{{- $name := .Values.metadata.name -}}
{{- $allowDots := default false .Values.advanced.common.app_chart.values.allow_dots_in_env -}}
{{- $excludes := .Values.advanced.common.app_chart.values.exclude_env_and_secret_values | default (list) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-chart.metadataLabels" . | nindent 4 }}
type: Opaque
data:
  {{- range $index, $value := .Values.spec.env }}
  {{- $skip := false -}}
  {{- range $excludes }}
    {{- if eq . $value }}
      {{- $skip = true }}
    {{- end }}
  {{- end }}
  {{- if not $skip }}
    {{- if and (regexMatch "[.]" $index) (not $allowDots) }}
    {{- $k := $index | upper | replace "." "_" }}
      {{ $k }}: {{ $value | default "" | toString | b64enc | default ("" | quote) }}
    {{- else }}
      {{ $index }}: {{ $value | default "" | toString | b64enc | default ("" | quote) }}
    {{- end }}
  {{- end }}
  {{- end }}