{{- $name := .Values.metadata.name -}}
{{- $allowDots := default false .Values.advanced.common.app_chart.values.allow_dots_in_env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-chart.metadataLabels" . | nindent 4 }}
type: Opaque
data:
  {{- range $index, $value := .Values.spec.env }}
  {{- if and (regexMatch "[.]" $index) (not $allowDots) }}
  {{- $k := $index | upper | replace "." "_" }}
    {{ $k }}: {{ $value | toString | b64enc | default ("" | quote) }}
  {{- else }}
    {{ $index }}: {{ $value | toString | b64enc | default ("" | quote) }}
  {{- end }}
  {{- end }}